### PR TITLE
fix(export): improve performance of spreadsheet export and fix simultaneous exports

### LINKED ISSUE #422: Spreadsheet Export Slow or Fails
The export of projects or projects with releases is slow or breaks. tested with 700 projects and their releases. Waiting time is somewhat in 10,20,30 minutes.

Also use of filtering should be tested:
Steps for reproduction:
* Use the tag value in the filter section
* Hit 'Apply'
* Select 'Projects with Linked releases' and hit 'Export Spreadsheet'

Expected:
Export filtered by projects tagged with tag value

### PR DESCRIPTION
**Pull request by alexbrdn**
- use streaming poi api to improve performance of spreadsheet export with many documents
- preload related data in ExcelExporters to reduce roundtrips to DB
- enable simultaneous parallel exports (they were mangled by usage of static fields)
- delete unused field Project.releaseIds

closes #422

### CODE REVIEW

**Comment by maximilianhuber** [comment]
@alexbrdn 
There is a test that fails:

**Comment by alexbrdn** [comment]
My bad. So much about relying on Travis to run all the tests :/

**Comment by alexbrdn** [comment]
@maximilianhuber , the test's fixed

File: libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ExporterHelper.java [hunk 1]
```diff
@@ -20,10 +22,20 @@
  */
 public interface ExporterHelper<T> {
 
-    public int getColumns();
+    static List<String> addSubheadersWithPrefixesAsNeeded(List<String> headers, List<String> subheaders, String prefix) {
+        List<String> prefixedSubheaders = subheaders
+                .stream()
+                .map(h -> headers.contains(h) ? prefix + h : h)
```
Comment (alexbrdn) [inline libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ExporterHelper.java]: Releases have substructures like clearingInformation, for example. If I were to prefix all subheaders, we'd get some really long headers like `release: clearing information: componentLicenseInformation`. I didn't like that prospect, so I decided to only prefix duplicate headers.

**Comment by mcjaeger** [comment]
speedwise it is just another dimension: exporting thousands of components (only) is done in 5.6 secs. with releases  not much more resulting in 3.3MB of spreadsheet data. project export of several hundreds, 2.39 secs. wow.
