### PR TITLE
fix(ui): Changing content of vendorNames to be vendor short names

### LINKED ISSUE #355: Use vendor short name for listings
Vendors have vendor short name and vendor long name. For the listing there is the long name confusing: for example "Apache Software Foundation", where the "Apache" would be enough.

### PR DESCRIPTION
**Pull request by stevinus1**
Showing vendor short name rather than vendor long name in component listings by changing the content of the vendorNames field,

closes #355

### CODE REVIEW

**Comment by mcjaeger** [comment]
seems to work for the project part, but .. I see that issue #335 was not well described ... could you pls. consider changing that in components as well?

attached an example for the main listing of components where the long name (=apache software foundation) instead of the short name (=apache) is used, but the short name would be a better fit here.

screen shot 2017-07-25 at 17 17 42

File: libraries/importers/component-importer/src/main/java/org/eclipse/sw360/importer/ComponentImportUtils.java [hunk 1]
```diff
@@ -469,9 +469,21 @@ public ReleaseLinkCSVRecord apply(CSVRecord input) {
...
         Map<String, String> vendorNameToVendorId = new HashMap<>();
 
-        for (Vendor vendor : vendorClient.getAllVendors()) {
-            vendorNameToVendorId.put(vendor.getFullname(), vendor.getId());
-        }
+            for (Vendor vendor : vendorClient.getAllVendors()) {
+                if (!vendorNameToVendorId.containsKey(vendor.getShortname())) {
+                    vendorNameToVendorId.put(vendor.getShortname(), vendor.getId());
+                }
+                else {
```
Comment (alexbrdn) [inline libraries/importers/component-importer/src/main/java/org/eclipse/sw360/importer/ComponentImportUtils.java]: That's an unusual formatting. The convention is to place `else` on the same line as the previous closing curly brace. Like this: `} else {`.
Same goes for line 482

File: libraries/importers/component-importer/src/main/java/org/eclipse/sw360/importer/ComponentImportUtils.java [hunk 2]
```diff
@@ -469,9 +469,21 @@ public ReleaseLinkCSVRecord apply(CSVRecord input) {
...
+                    log.error("There is a clash between the shortname " + vendor.getShortname() + " and a name already present in the mapping.");
```
Comment (alexbrdn) [inline libraries/importers/component-importer/src/main/java/org/eclipse/sw360/importer/ComponentImportUtils.java]: Is it really an error, if you just ignore it and proceed anyway? Maybe you want to log it as a warning?

But that's more of a philosophical question than a call to action, because this module for components csv export should be removed altogether. It's a dead feature. It's slow to the point of being unusable with large amounts of data and no one uses it anyways.
